/// 敵の種族（見た目 look ごと）。図鑑・演出・SE に使う。
///
/// ゲームの敵は「文房具 × 生き物・職業・ファンタジー」の組み合わせで、
/// 同じ種族でもエリアごとに名前・色・セリフが変わる（EnemyDef）。

enum SpeciesCategory {
  writing('筆記具系', '✎'),
  paper('紙・ノート系', '📄'),
  measure('計測・製図系', '📐'),
  crafting('整理・加工系', '✂'),
  school('学校用品系', '🎒'),
  ancient('古き魔物系', '🗝'),
  sea('海の魔物系', '🌊'),
  sky('空の魔物系', '☁');

  const SpeciesCategory(this.label, this.mark);
  final String label;
  final String mark;
}

enum SpeciesSize {
  small('小型'),
  medium('中型'),
  large('大型');

  const SpeciesSize(this.label);
  final String label;
}

/// レア度。色だけでなく、枠の形・星の数・名前でも区別する
enum Rarity {
  common('COMMON', 1),
  rare('RARE', 2),
  epic('EPIC', 3),
  legendary('LEGENDARY', 4);

  const Rarity(this.label, this.stars);
  final String label;
  final int stars;
}

class EnemySpecies {
  const EnemySpecies({
    required this.look,
    required this.name,
    required this.motif,
    required this.category,
    required this.size,
    required this.rarity,
    required this.personality,
    required this.attack,
    required this.lore,
    required this.sound,
  });

  /// 描画のキー（EnemyDef.look と同じ）
  final String look;

  /// 種族名
  final String name;

  /// 何と何の組み合わせか（例：鉛筆 × 槍兵）
  final String motif;
  final SpeciesCategory category;
  final SpeciesSize size;
  final Rarity rarity;

  /// 性格
  final String personality;

  /// 攻撃のしかた
  final String attack;

  /// 図鑑の説明
  final String lore;

  /// 固有 SE のキー（assets/audio/se/<sound>.mp3）
  final String sound;
}

class EnemySpeciesCatalog {
  const EnemySpeciesCatalog._();

  static const all = <EnemySpecies>[
    EnemySpecies(
      look: 'eraser',
      name: 'ケシゴムン',
      motif: '消しゴム × スライム',
      category: SpeciesCategory.writing,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'まちがいを見つけると、うれしそうにはねる',
      attack: '体当たりで答えをこすり消し、消しカスをまき散らす',
      lore: '机の角で削れた角を気にしている。消したはずの答えを、ときどきこっそり覚えている。',
      sound: 'se_rub',
    ),
    EnemySpecies(
      look: 'crayon',
      name: 'クレヨンぶんぶん',
      motif: 'クレヨン × 羽虫',
      category: SpeciesCategory.writing,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '落ち着きがなく、同じ色で二度描かない',
      attack: '色の軌跡を引いて、問題文をぐちゃぐちゃに塗る',
      lore: '12色の群れで飛ぶ。いちばん短くなった一本が群れの長になるらしい。',
      sound: 'se_scribble',
    ),
    EnemySpecies(
      look: 'sticky',
      name: 'フセンチョウ',
      motif: '付箋 × 蝶',
      category: SpeciesCategory.paper,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '大事なところにだけ、ひらりと止まる',
      attack: '顔にはりついて視界をふさぐ',
      lore: '「ここ重要」の羽をもつ。はがすと、なぜかその単元が気になってくる。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'pencil',
      name: 'エンピツランサー',
      motif: '鉛筆 × 槍兵',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: 'まっすぐで、削られるほど強気になる',
      attack: 'とがった芯で一直線に突く',
      lore: '芯の硬さで性格が変わる。HB は真面目、2B は情熱的、H は冷静。',
      sound: 'se_scratch',
    ),
    EnemySpecies(
      look: 'stubpencil',
      name: 'ちびエンピツ老兵',
      motif: '短い鉛筆 × 老兵',
      category: SpeciesCategory.writing,
      size: SpeciesSize.small,
      rarity: Rarity.rare,
      personality: '昔の試験の話ばかりする',
      attack: '長年の経験で、ひっかけ問題をしかける',
      lore: '何百枚ものノートを書ききった歴戦の鉛筆。補助軸の杖をついている。',
      sound: 'se_scratch',
    ),
    EnemySpecies(
      look: 'pen',
      name: 'ボールペン剣士',
      motif: 'ボールペン × 剣士',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '一度書いたことは曲げない頑固者',
      attack: 'ノックして芯を出し、居合い斬り',
      lore: '消せないインクが誇り。まちがえたときは二重線で潔く訂正する。',
      sound: 'se_click',
    ),
    EnemySpecies(
      look: 'mechpencil',
      name: 'シャーペンロボ',
      motif: 'シャープペンシル × ロボット',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '几帳面で、0.5 mm 単位で計算する',
      attack: 'ノックのたびに芯のミサイルを発射する',
      lore: '内部に芯のストックを12本持つ。折れても次がすぐ出てくる。',
      sound: 'se_click',
    ),
    EnemySpecies(
      look: 'marker',
      name: '蛍光ペンウィザード',
      motif: '蛍光ペン × 魔法使い',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '大事なことを光らせずにはいられない',
      attack: '蛍光インクの魔法陣で、答えを見えにくくする',
      lore: '引いた線が光って浮かび上がる。引きすぎると、何が大事か分からなくなる。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'ruler',
      name: '定規ナイト',
      motif: '定規 × 騎士',
      category: SpeciesCategory.measure,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '曲がったことが大きらい',
      attack: '目盛りの剣でまっすぐ斬りつける',
      lore: '30 cm の剣を持つ。1 mm のずれも見のがさない正確さが自慢。',
      sound: 'se_slash',
    ),
    EnemySpecies(
      look: 'triangle',
      name: '三角定規シールダー',
      motif: '三角定規 × 盾兵',
      category: SpeciesCategory.measure,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '二人一組で行動する（30°・60°と45°の兄弟）',
      attack: '直角の盾で攻撃をはね返す',
      lore: '2枚を組み合わせると、どんな平行線でも引ける。仲間思い。',
      sound: 'se_block',
    ),
    EnemySpecies(
      look: 'protractor',
      name: '分度器メイジ',
      motif: '分度器 × 魔術師',
      category: SpeciesCategory.measure,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '角度にうるさい理屈屋',
      attack: '半円の魔法陣から、180度の光線を放つ',
      lore: '目盛りの内側と外側を読みまちがえた者を、容赦なく笑う。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'compass',
      name: 'コンパススパイダー',
      motif: 'コンパス × クモ',
      category: SpeciesCategory.measure,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '中心を決めたら、一歩も動かない',
      attack: '針の脚で円をえがき、幾何学の巣に閉じこめる',
      lore: '完全な円の巣をはる。半径が少しでもずれると、作り直すまで眠れない。',
      sound: 'se_scratch',
    ),
    EnemySpecies(
      look: 'stapler',
      name: 'ホッチキスクラブ',
      motif: 'ホッチキス × カニ',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: 'まとめたがり。ばらばらの紙を見ると落ち着かない',
      attack: '「カチッ」と閉じる口で、針を撃ちこむ',
      lore: '横歩きで机の上をうろつく。針が切れると急におとなしくなる。',
      sound: 'se_staple',
    ),
    EnemySpecies(
      look: 'scissors',
      name: 'ハサミビートル',
      motif: 'はさみ × カブトムシ',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '白黒はっきりつけたい',
      attack: '二本の刃の角で、問題文を切りきざむ',
      lore: '左右の刃は別々の意思をもつが、閉じる瞬間だけは息が合う。',
      sound: 'se_snip',
    ),
    EnemySpecies(
      look: 'binder',
      name: 'バインダートータス',
      motif: 'バインダー × 亀',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: 'のんびりしているが、なんでも覚えている',
      attack: '金具の甲羅をばちんと閉じて、はさみこむ',
      lore: '甲羅の中に、これまで出会ったすべてのプリントを保管している。',
      sound: 'se_snap',
    ),
    EnemySpecies(
      look: 'page',
      name: 'プリント兵',
      motif: 'プリント × 紙兵',
      category: SpeciesCategory.paper,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '配られるとすぐ整列する',
      attack: '紙飛行機になって突撃する',
      lore: '名前を書き忘れると、持ち主のもとに帰れなくなる。',
      sound: 'se_page',
    ),
    EnemySpecies(
      look: 'ghost',
      name: 'ノートゴースト',
      motif: 'ノート × 幽霊',
      category: SpeciesCategory.paper,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '書かれなかった答えの未練でできている',
      attack: 'ページをめくる風で、記憶をあいまいにする',
      lore: '白紙のページほど強い。一度でも書きこまれると、少しだけ満足する。',
      sound: 'se_ghost',
    ),
    EnemySpecies(
      look: 'book',
      name: '魔導教科書',
      motif: '教科書 × 魔導書',
      category: SpeciesCategory.paper,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '知識を独り占めしたがる',
      attack: '重要語句を呪文のように唱え、ページで押しつぶす',
      lore: '索引から自在に章を呼び出す。最後まで読んだ者にだけ心を開く。',
      sound: 'se_page',
    ),
    EnemySpecies(
      look: 'bat',
      name: 'しおりコウモリ',
      motif: 'しおり × コウモリ',
      category: SpeciesCategory.paper,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '途中でやめたページにぶら下がる',
      attack: '超音波で「どこまで読んだっけ」と迷わせる',
      lore: '読みかけの本にすみつく。最後まで読むと、どこかへ飛んでいく。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'slime',
      name: 'のりスライム',
      motif: 'スティックのり × スライム',
      category: SpeciesCategory.school,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'くっつきたがりで、寂しがり',
      attack: 'べたべたの体で動きを止める',
      lore: '乾くと固まって動けなくなる。キャップを閉めると安心して眠る。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'goblin',
      name: 'クリップ小鬼',
      motif: 'ゼムクリップ × 小鬼',
      category: SpeciesCategory.school,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'いたずら好きで、プリントの順番を入れかえる',
      attack: '曲げたクリップの鉤爪でひっかく',
      lore: '一本の針金を曲げて体を作っている。のばすと元に戻れない。',
      sound: 'se_click',
    ),
    EnemySpecies(
      look: 'golem',
      name: 'ぶんちんゴーレム',
      motif: '文鎮 × ゴーレム',
      category: SpeciesCategory.school,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '重くて動かない。動くときは本気',
      attack: '全体重で押さえつける',
      lore: '書道の時間から生まれた。半紙を押さえる役目を、今も律儀に守っている。',
      sound: 'se_thud',
    ),
    EnemySpecies(
      look: 'knight',
      name: 'ペーパーナイト',
      motif: 'ペーパーナイフ × 騎士',
      category: SpeciesCategory.ancient,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '礼儀正しく、封を切る前に必ず一礼する',
      attack: '封を開くように、守りを切り開く',
      lore: '手紙を開けるための刃を持つ騎士。知識の封印を守ってきた。',
      sound: 'se_slash',
    ),
    EnemySpecies(
      look: 'dragon',
      name: '万年筆ドラゴン',
      motif: '万年筆 × ドラゴン',
      category: SpeciesCategory.ancient,
      size: SpeciesSize.large,
      rarity: Rarity.legendary,
      personality: '誇り高く、自分の書いた文字を愛している',
      attack: 'インクの炎を吐き、ペン先の爪で刻む',
      lore: '何百年も書き続けてきた古いペン先が竜になった。そのインクは乾かない。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'jellyfish',
      name: 'うっかりクラゲ',
      motif: 'クラゲ × うっかりミス',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'ぼんやりしていて、いつの間にか近くにいる',
      attack: 'ふわりと刺して、頭をぼんやりさせる',
      lore: '定期テストの海をただよう。見直しをしない答案に集まってくるらしい。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'crab',
      name: 'ひっかけガニ',
      motif: 'カニ × ひっかけ問題',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '横歩きで、正面から勝負しない',
      attack: 'はさみで答えをひっかけ、ちょきんと切りかえる',
      lore: '「すべて選べ」「誤っているものを」を読み落とした人のところへ、横から寄ってくる。',
      sound: 'se_snip',
    ),
    EnemySpecies(
      look: 'puffer',
      name: 'ふくれっつらフグ',
      motif: 'フグ × ふくれっつら',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.rare,
      personality: 'すぐにふくれるが、根はやさしい',
      attack: 'ぷくっとふくれて、トゲで体当たり',
      lore: '範囲が発表されると、あまりの広さにふくれてしまう。しぼむと小さくてかわいい。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'shark',
      name: '赤点ザメ',
      motif: 'サメ × 赤点',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '赤点のにおいに敏感で、しつこい',
      attack: '続けざまにかみついて、点数をけずる',
      lore: '水中で数キロ先の赤点をかぎわける。正解が続くと、においを見失って逃げていく。',
      sound: 'se_slash',
    ),
    EnemySpecies(
      look: 'octopus',
      name: '暗記ダコ',
      motif: 'タコ × 丸暗記',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '8つのことを同時に考えられる自信家',
      attack: '墨をはいて、問題文を黒くぬりつぶす',
      lore: '8本の足でそれぞれ用語を覚えている。ただし足どうしがつながっていないので、応用は苦手。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'angler',
      name: '深海アンコウ',
      motif: 'チョウチンアンコウ × わかったつもり',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.epic,
      personality: '暗がりで、じっと待つのが得意',
      attack: 'ちょうちんの光で「わかったつもり」を誘い、ぱくりと飲みこむ',
      lore: '深海の暗闇で、あいまいな知識を光らせて獲物を集める。本当にわかっている人には光が効かない。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'squid',
      name: 'ダイオウ難問イカ',
      motif: 'ダイオウイカ × 長文問題',
      category: SpeciesCategory.sea,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: 'ゆっくりだが、つかんだらはなさない',
      attack: '長い触手で長い問題をからませる',
      lore: '深海の奥にひそむ。触手の吸盤ひとつひとつに、長文の段落が書かれている。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'leviathan',
      name: '範囲の海竜リヴァイアサン',
      motif: '海竜 × 試験範囲',
      category: SpeciesCategory.sea,
      size: SpeciesSize.large,
      rarity: Rarity.legendary,
      personality: 'おごそかで、試験範囲のすべてを守る',
      attack: '大波で範囲のすべてを押しよせさせる',
      lore: '定期テストの海の底で眠る海竜。範囲の最後のページが、その背びれになっている。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'cloudling',
      name: '雨雲ぼうず',
      motif: '雨雲 × 集中切れ',
      category: SpeciesCategory.sky,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'きまぐれで、すぐに泣きだす',
      attack: '雨をふらせて、集中をじゃまする',
      lore: '高校入試の空にうかぶ小さな雨雲。テスト中に窓の外が気になるのは、こいつのせい。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'bird',
      name: '偏差値ガラス',
      motif: 'カラス × 偏差値',
      category: SpeciesCategory.sky,
      size: SpeciesSize.small,
      rarity: Rarity.rare,
      personality: '数字を集めるのが大好き',
      attack: '連続でつついて、判定を下げる',
      lore: '光る数字を巣に集める黒い鳥。いちばん大事にしているのは、自分の偏差値。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'thunder',
      name: '雷鳴のカミナリ玉',
      motif: '雷 × 一発勝負',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: 'ゴロゴロと気が短い',
      attack: '一問のまちがいに雷を落とす',
      lore: '一問のミスもゆるさない。続けて正解すると、雷が静まって小さくなる。',
      sound: 'se_thud',
    ),
    EnemySpecies(
      look: 'wyvern',
      name: '模試ワイバーン',
      motif: 'ワイバーン × 模試会場',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '誇り高く、会場の空を守る',
      attack: '急降下して、かたいつばさで打ちすえる',
      lore: '模試の会場の上をまわりつづける翼竜。うろこの一枚一枚が、過去の模試の解答用紙。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'meteor',
      name: '隕石ゴーレム',
      motif: '隕石 × ゴーレム',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.rare,
      personality: '無口で、とにかく重い',
      attack: '燃えながら落ちてきて、押しつぶす',
      lore: '宇宙から落ちてきた岩のかたまり。中には、昔だれかが解けなかった問題が閉じこめられている。',
      sound: 'se_thud',
    ),
    EnemySpecies(
      look: 'ufo',
      name: 'E判定UFO',
      motif: 'UFO × 判定',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.epic,
      personality: 'ぴかぴか光って、落ちつきがない',
      attack: '判定の光線をあびせ、むずかしい問題を呼びよせる',
      lore: '模試の判定を運んでくる謎の円盤。光線をよけきると、判定がひとつ上がるという。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'astral',
      name: '天空の審判アストラル',
      motif: '星座 × 審判',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.legendary,
      personality: 'すべてを見とおし、公平に判定する',
      attack: '星をつないだ光の線で、答えの正しさを見ぬく',
      lore: '高校入試の空の果て、星の海にいる審判。その目に映るのは、点数ではなく本当の実力。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'notebook',
      name: 'ノートン',
      motif: '大学ノート × 図書委員',
      category: SpeciesCategory.paper,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: 'まじめで、書いたことは何でも覚えている',
      attack: '分厚いページで体当たりし、ページをめくって次々と問題を出す',
      lore: '授業の内容をぜんぶ書きうつした一冊。ぶあつい体は、ちょっとやそっとの攻撃では破れない。',
      sound: 'se_page',
    ),
    EnemySpecies(
      look: 'pencilcase',
      name: 'フデバコング',
      motif: '筆箱 × ゴリラ',
      category: SpeciesCategory.school,
      size: SpeciesSize.large,
      rarity: Rarity.rare,
      personality: '面倒見がよく、仲間を呼ぶのが得意',
      attack: 'ふたを開けると、中の文房具たちが次々と飛び出してくる',
      lore: '筆箱の中の文房具をまとめる親分。一体ずつ倒しても、すぐに次の仲間が出てくる。',
      sound: 'se_thud',
    ),
    EnemySpecies(
      look: 'glue',
      name: 'ノリノリスティック',
      motif: 'スティックのり × ダンサー',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'いつもノリがよく、くっついて離れない',
      attack: 'ねばねばの体で答えを貼りつけ、連続で正解しないとはがれない',
      lore: 'まちがった知識でも貼りつけてしまう困りもの。二度続けて正しく答えると、ようやくはがれる。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'tape',
      name: 'セロテープス',
      motif: 'セロハンテープ × 輪っか',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '気まぐれで、つながりを切るのが好き',
      attack: 'テープでぐるぐる巻きにして、勢いを止める',
      lore: '調子に乗った連続正解を見つけると、テープでぷつんと切ってしまう。むすびの栞には弱い。',
      sound: 'se_snap',
    ),
    EnemySpecies(
      look: 'clip',
      name: 'クリップマン',
      motif: 'ゼムクリップ × 体操選手',
      category: SpeciesCategory.crafting,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '身軽で、じっとしていられない',
      attack: 'ばねのように跳ねまわり、ゆっくり考えた答えをかわす',
      lore: 'プリントを束ねるのが本業。考えこんでいるすきに、ぴょんと跳ねてよけてしまう。',
      sound: 'se_click',
    ),
    EnemySpecies(
      look: 'pushpin',
      name: 'ガビョウニ',
      motif: '画びょう × 番兵',
      category: SpeciesCategory.school,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '頑固で、決めた場所から動かない',
      attack: 'とがった針で一点を刺す。弱点の問題にはめっぽう弱い',
      lore: '掲示板の要点を守る番兵。急所の分野を突かれると、ぽろりと抜け落ちる。',
      sound: 'se_slash',
    ),
    EnemySpecies(
      look: 'sharpener',
      name: 'ケズリドン',
      motif: '鉛筆削り × 鍛冶屋',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '職人気質で、鋭さにこだわる',
      attack: 'ハンドルを回して、問題をとがらせて飛ばす',
      lore: '問題を削って鋭くする鍛冶屋。弱点を突くまでは、硬い箱でダメージを半分にする。',
      sound: 'se_scratch',
    ),
    EnemySpecies(
      look: 'brush',
      name: 'フデマル',
      motif: '習字の筆 × 書道家',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '静かで、一筆にすべてをこめる',
      attack: '墨のしずくを飛ばして、次の問題をにじませる',
      lore: 'まちがえると墨をはねて、次の問題を読みにくくする。落ち着いて一字ずつ読めば怖くない。',
      sound: 'se_scribble',
    ),
    EnemySpecies(
      look: 'correction',
      name: 'シュウセイテープ',
      motif: '修正テープ × 掃除屋',
      category: SpeciesCategory.writing,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'きれい好きで、何でも白く消したがる',
      attack: '白い帯でコンボを消し、勢いをなかったことにする',
      lore: 'まちがいを消すのは得意だが、正しい連続正解まで消してしまう。',
      sound: 'se_rub',
    ),
    EnemySpecies(
      look: 'inkpot',
      name: 'インクボトル',
      motif: 'インク瓶 × 魔法使い',
      category: SpeciesCategory.writing,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: 'いたずら好きで、答えを黒く塗りたがる',
      attack: 'インクの波で問題文を塗りつぶし、難しい問題を呼ぶ',
      lore: '古い羽ペンの時代から生きている。まちがえると、次の問題を真っ黒なインクで難しくする。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'calculator',
      name: 'デンタクン',
      motif: '電卓 × ロボット',
      category: SpeciesCategory.measure,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '計算は速いが、考えるのは苦手',
      attack: 'ボタンの目を光らせ、数字の弾を打ちこむ',
      lore: '計算問題には強いが、苦手な分野を突かれると画面がエラー表示になる。',
      sound: 'se_click',
    ),
    EnemySpecies(
      look: 'ray',
      name: 'ヒラメキエイ',
      motif: 'エイ × ひらめき',
      category: SpeciesCategory.sea,
      size: SpeciesSize.large,
      rarity: Rarity.rare,
      personality: 'ゆったりしているが、逃げ足は速い',
      attack: '大きなひれで水をすべり、もたもたした答えをかわす',
      lore: 'ひらめきの速さを試す海の魔物。迷っているあいだに、すいっと泳ぎ去ってしまう。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'turtle',
      name: 'ノンビリガメ',
      motif: 'ウミガメ × 長老',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: 'のんびり屋で、何百年も同じ海を泳いでいる',
      attack: '方眼もようの甲らで攻撃を受け流す',
      lore: '甲らのマス目には、これまで出題された問題が記録されているという。',
      sound: 'se_block',
    ),
    EnemySpecies(
      look: 'whale',
      name: 'モノシリクジラ',
      motif: 'クジラ × 博士',
      category: SpeciesCategory.sea,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '物知りで、話しだすと止まらない',
      attack: '潮といっしょに知識の泡をふき出す',
      lore: '海でいちばん大きな体に、あらゆる教科の知識をためている。ダメージが通りにくい。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'seahorse',
      name: 'タツノシルベ',
      motif: 'タツノオトシゴ × 道しるべ',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: '気が小さいが、道案内は得意',
      attack: 'しっぽで矢印を描き、じっくり考えた答えをかわす',
      lore: 'まっすぐ立って泳ぐ海の道しるべ。すばやく答えれば、案内の矢印が正解を指す。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'starfish',
      name: 'ホシノカケラ',
      motif: 'ヒトデ × 星座',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'にぎやかで、いつも仲間といっしょ',
      attack: '5本の腕で手をつなぎ、仲間を次々と呼ぶ',
      lore: '夜の浜辺で光る星のかけら。3体で1つの星座を作り、1体が弱ると次が現れる。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'eel',
      name: 'ウツボルト',
      motif: 'ウツボ × 稲妻',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: 'ふだんは岩かげでじっとしている',
      attack: '急に飛び出してかみつく。連続で正解するとくずれる',
      lore: '一撃一撃は効きにくいが、連続正解の勢いに弱い。',
      sound: 'se_snap',
    ),
    EnemySpecies(
      look: 'ammonite',
      name: 'アンモナイト博士',
      motif: 'アンモナイト × 古生物学者',
      category: SpeciesCategory.sea,
      size: SpeciesSize.medium,
      rarity: Rarity.epic,
      personality: '古い時代のことにくわしく、片めがねがお気に入り',
      attack: 'うずまきの殻にこもり、弱点を突かれるまで守りを固める',
      lore: '深海で化石から目覚めた博士。殻のうずに、地球の歴史が年代順に刻まれている。',
      sound: 'se_block',
    ),
    EnemySpecies(
      look: 'urchin',
      name: 'トゲトゲウニ',
      motif: 'ウニ × 針山',
      category: SpeciesCategory.sea,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'ぶっきらぼうだが、根はやさしい',
      attack: 'とげを伸ばしてダメージを受け流す',
      lore: '海の底で、とげを呼吸のように伸び縮みさせている。',
      sound: 'se_thud',
    ),
    EnemySpecies(
      look: 'angel',
      name: 'テンシノシオリ',
      motif: '天使 × しおり',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: 'おだやかで、読みかけのページを守る',
      attack: '光の輪で、得意な分野以外の答えをはね返す',
      lore: '空の図書館を守る天使。弱点の分野を見ぬかれると、しおりの羽が抜け落ちる。',
      sound: 'se_magic',
    ),
    EnemySpecies(
      look: 'owl',
      name: 'ハクシキフクロウ',
      motif: 'フクロウ × 教授',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '博識で、首をかしげてじっと見る',
      attack: 'まちがえた相手に、さらに難しい問題を出す',
      lore: '夜の雲海で講義をしているフクロウ。まちがえると「では、これは？」と難問を出してくる。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'phoenix',
      name: 'フェニックス',
      motif: '不死鳥 × 赤ペン',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '誇り高く、何度でもよみがえる',
      attack: '赤ペンの炎で答えを採点し、炎の翼でダメージを受け流す',
      lore: '赤ペン先生の炎から生まれた鳥。まちがいを直すたびに、新しく生まれ変わる。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'pegasus',
      name: 'ペガサスパート',
      motif: 'ペガサス × 楽譜',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.rare,
      personality: '気高く、拍子に合わせて駆ける',
      attack: '蹄の音で拍子をとり、遅れた答えをかわす',
      lore: '五線譜の雲を駆けるペガサス。テンポよく答えないと、追いつけない。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'balloon',
      name: 'フウセンオバケ',
      motif: '風船 × おばけ',
      category: SpeciesCategory.sky,
      size: SpeciesSize.small,
      rarity: Rarity.common,
      personality: 'ふわふわして、すぐどこかへ行きたがる',
      attack: 'ふわりと浮かんで、考えこんだ答えをかわす',
      lore: 'ひもの先に忘れ物をつけて飛んでいる。つかまえるには、すばやさが必要。',
      sound: 'se_ghost',
    ),
    EnemySpecies(
      look: 'kite',
      name: 'タコアゲ',
      motif: '凧 × 問題用紙',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.common,
      personality: '風まかせで、気分屋',
      attack: 'しっぽの札で勢いを切り、コンボを止める',
      lore: 'しっぽに「問一」「問二」の札をつけて空を舞う。連続正解の勢いを、風で吹き飛ばす。',
      sound: 'se_flap',
    ),
    EnemySpecies(
      look: 'griffin',
      name: 'グリフォンガード',
      motif: 'グリフォン × 門番',
      category: SpeciesCategory.sky,
      size: SpeciesSize.large,
      rarity: Rarity.epic,
      personality: '忠実で、宝の問題を守る',
      attack: '鋭いくちばしで守りを固め、弱点を突かれるまでダメージを半分にする',
      lore: 'わしの頭としし体をもつ、知識の宝物庫の門番。',
      sound: 'se_roar',
    ),
    EnemySpecies(
      look: 'rainbow',
      name: 'ニジヘビ',
      motif: 'ヘビ × 虹',
      category: SpeciesCategory.sky,
      size: SpeciesSize.medium,
      rarity: Rarity.rare,
      personality: '色とりどりの気分で、気まぐれ',
      attack: '7色の帯で体を守り、2問続けて正解しないと効かない',
      lore: '7色の問題を順に出すという空のヘビ。虹の橋の下に住んでいる。',
      sound: 'se_squish',
    ),
    EnemySpecies(
      look: 'mimic',
      name: 'ミミック',
      motif: '宝箱 × 魔物',
      category: SpeciesCategory.school,
      size: SpeciesSize.medium,
      rarity: Rarity.epic,
      personality: 'いたずら好きで、だますのが生きがい',
      attack: '宝箱のふりをして待ち、最初の問題で不意打ちする',
      lore: '宝箱だと思って開けた冒険者を待ちかまえている。最初の1問を落ち着いて答えれば、怖くない。',
      sound: 'se_snap',
    ),
  ];

  static final _byLook = {for (final s in all) s.look: s};

  /// 見た目のキーから種族を返す（未知なら のりスライム）
  static EnemySpecies of(String look) => _byLook[look] ?? _byLook['slime']!;
}
