import '../models/stage.dart';

/// マップの組み立て方（地形ごとに変える）
enum Layout {
  /// ひらけた土地に、木や岩がぽつぽつある
  open,

  /// 木や岩がかたまって、くねくねした道になる（森・洞窟）
  dense,

  /// 川・海・雲の切れ目を、橋でわたる
  water,

  /// 柱・本棚・家などが規則正しく並ぶ（建物の中や町）
  grid,
}

/// エリアの地形。エリアの名前（「ばねの林」「助動詞の関所」など）から決まり、
/// 床・障害物・壁・水の見た目と、マップの組み立て方が変わる。
enum Terrain {
  meadow('草原', Layout.open),
  flower('花畑', Layout.open),
  forest('森', Layout.dense),
  hill('丘', Layout.open),
  river('水辺', Layout.water),
  beach('海辺', Layout.water),
  cave('洞窟', Layout.dense),
  crystal('地底湖', Layout.dense),
  ruins('遺跡', Layout.grid),
  shrine('殿堂', Layout.grid),
  harbor('港', Layout.water),
  town('町', Layout.grid),
  workshop('工房', Layout.grid),
  library('書庫', Layout.grid),
  tower('塔', Layout.grid),
  sky('空', Layout.water),
  snow('雪原', Layout.open),
  desert('砂漠', Layout.open),
  lava('火山', Layout.dense),
  castle('城', Layout.grid);

  const Terrain(this.label, this.layout);
  final String label;
  final Layout layout;

  /// 名前にふくまれる言葉 → 地形（上から順に探す。長い言葉・特別な言葉を先に）
  static const _keywords = <(String, Terrain)>[
    ('玉座', castle),
    ('天守', castle),
    ('要塞', castle),
    ('とりで', castle),
    ('石塁', castle),
    ('壁', castle),
    ('火口', lava),
    ('戦線', desert),
    ('塹壕', desert),
    ('三日月', desert),
    ('歯車', workshop),
    ('風車', workshop),
    ('地下水路', crystal),
    ('岩窟', cave),
    ('見張り台', tower),
    ('天文台', tower),
    ('月見台', tower),
    ('楼閣', tower),
    ('闘技場', ruins),
    ('舞台', ruins),
    ('跡', ruins),
    ('迷路', ruins),
    ('議事堂', shrine),
    ('議場', shrine),
    ('会議', shrine),
    ('法廷', shrine),
    ('奉行所', shrine),
    ('十二単', shrine),
    ('館', shrine),
    ('聖地', shrine),
    ('金庫', shrine),
    ('病院', town),
    ('官庁街', town),
    ('街', town),
    ('宿場', town),
    ('村', town),
    ('石畳', town),
    ('波止場', harbor),
    ('渡し場', harbor),
    ('桟橋', harbor),
    ('黒船', harbor),
    ('岸辺', harbor),
    ('滝', river),
    ('坂', hill),
    ('階段', hill),
    ('崖', hill),
    ('尾根', hill),
    ('峰', hill),
    ('台地', hill),
    ('高台', hill),
    ('岐路', forest),
    ('古道', forest),
    ('庭', flower),
    ('城', castle),
    ('砦', castle),
    ('炎', lava),
    ('溶岩', lava),
    ('火山', lava),
    ('マグマ', lava),
    ('焼け', lava),
    ('鍛冶', workshop),
    ('工場', workshop),
    ('工房', workshop),
    ('水車', workshop),
    ('からくり', workshop),
    ('坑道', cave),
    ('鉱山', cave),
    ('地底湖', crystal),
    ('鏡', crystal),
    ('結晶', crystal),
    ('空洞', cave),
    ('洞窟', cave),
    ('洞', cave),
    ('穴', cave),
    ('塔', tower),
    ('灯台', tower),
    ('時計', tower),
    ('書庫', library),
    ('図書', library),
    ('学堂', library),
    ('文庫', library),
    ('書', library),
    ('回廊', ruins),
    ('遺跡', ruins),
    ('神殿', ruins),
    ('石段', ruins),
    ('迷宮', ruins),
    ('宮', shrine),
    ('御殿', shrine),
    ('関所', shrine),
    ('社', shrine),
    ('寺', shrine),
    ('門', shrine),
    ('大路', town),
    ('通り', town),
    ('銀座', town),
    ('交差点', town),
    ('広場', town),
    ('台所', town),
    ('市', town),
    ('町', town),
    ('里', town),
    ('都', town),
    ('港', harbor),
    ('浜', beach),
    ('入り江', beach),
    ('岬', hill),
    ('岩場', beach),
    ('海', beach),
    ('島', beach),
    ('谷', river),
    ('河', river),
    ('川', river),
    ('湖', river),
    ('水辺', river),
    ('湿原', river),
    ('三角州', river),
    ('沼', river),
    ('泉', river),
    ('橋', river),
    ('空', sky),
    ('霧', sky),
    ('雲', sky),
    ('星', sky),
    ('雪', snow),
    ('氷', snow),
    ('極', snow),
    ('砂', desert),
    ('荒野', desert),
    ('森', forest),
    ('林', forest),
    ('並木', forest),
    ('小道', forest),
    ('花', flower),
    ('園', flower),
    ('丘', hill),
    ('峠', hill),
    ('山', hill),
    ('高原', hill),
    ('畑', meadow),
    ('牧場', meadow),
    ('平野', meadow),
    ('草原', meadow),
    ('野', meadow),
  ];

  /// 名前から地形を決める。見つからなければ [fallback]
  static Terrain fromName(String name, {Terrain fallback = meadow}) {
    for (final (word, t) in _keywords) {
      if (name.contains(word)) return t;
    }
    return fallback;
  }

  /// ステージの地形。名前から、見つからなければ地方（草原・海岸など）から決める。
  /// ボスのエリアは地形はそのままで、マップ側で「ボスの間」の飾りがつく。
  static Terrain of(StageDef stage) =>
      fromName(stage.name, fallback: fromName(stage.region));
}
