// assets/words/tsuzutan_*.json から tool/tsuzutan_index.py で作った一覧。手で書きかえない。
part of 'tsuzutan.dart';

const _lists = <TsuzutanList>[
  TsuzutanList(
      id: 'tsuzutan_1_01',
      title: 'つづ単 基礎 1',
      level: 1,
      count: 200,
      first: "ability",
      last: "east"),
  TsuzutanList(
      id: 'tsuzutan_1_02',
      title: 'つづ単 基礎 2',
      level: 1,
      count: 200,
      first: "education",
      last: "mention"),
  TsuzutanList(
      id: 'tsuzutan_1_03',
      title: 'つづ単 基礎 3',
      level: 1,
      count: 200,
      first: "middle",
      last: "smart"),
  TsuzutanList(
      id: 'tsuzutan_1_04',
      title: 'つづ単 基礎 4',
      level: 1,
      count: 138,
      first: "smell",
      last: "yard"),
  TsuzutanList(
      id: 'tsuzutan_2_01',
      title: 'つづ単 標準 1',
      level: 2,
      count: 200,
      first: "abandon",
      last: "choke"),
  TsuzutanList(
      id: 'tsuzutan_2_02',
      title: 'つづ単 標準 2',
      level: 2,
      count: 200,
      first: "circumstance",
      last: "enormous"),
  TsuzutanList(
      id: 'tsuzutan_2_03',
      title: 'つづ単 標準 3',
      level: 2,
      count: 200,
      first: "ensure",
      last: "initial"),
  TsuzutanList(
      id: 'tsuzutan_2_04',
      title: 'つづ単 標準 4',
      level: 2,
      count: 200,
      first: "injection",
      last: "odd"),
  TsuzutanList(
      id: 'tsuzutan_2_05',
      title: 'つづ単 標準 5',
      level: 2,
      count: 200,
      first: "offend",
      last: "reveal"),
  TsuzutanList(
      id: 'tsuzutan_2_06',
      title: 'つづ単 標準 6',
      level: 2,
      count: 200,
      first: "revenge",
      last: "tidy"),
  TsuzutanList(
      id: 'tsuzutan_2_07',
      title: 'つづ単 標準 7',
      level: 2,
      count: 99,
      first: "tissue",
      last: "youth"),
  TsuzutanList(
      id: 'tsuzutan_3_01',
      title: 'つづ単 発展 1',
      level: 3,
      count: 200,
      first: "a range of",
      last: "archaeologist"),
  TsuzutanList(
      id: 'tsuzutan_3_02',
      title: 'つづ単 発展 2',
      level: 3,
      count: 200,
      first: "archaeology",
      last: "botanist"),
  TsuzutanList(
      id: 'tsuzutan_3_03',
      title: 'つづ単 発展 3',
      level: 3,
      count: 200,
      first: "botany",
      last: "commence"),
  TsuzutanList(
      id: 'tsuzutan_3_04',
      title: 'つづ単 発展 4',
      level: 3,
      count: 200,
      first: "commencement",
      last: "crunch"),
  TsuzutanList(
      id: 'tsuzutan_3_05',
      title: 'つづ単 発展 5',
      level: 3,
      count: 200,
      first: "crunchy",
      last: "distort"),
  TsuzutanList(
      id: 'tsuzutan_3_06',
      title: 'つづ単 発展 6',
      level: 3,
      count: 200,
      first: "distortion",
      last: "evident"),
  TsuzutanList(
      id: 'tsuzutan_3_07',
      title: 'つづ単 発展 7',
      level: 3,
      count: 200,
      first: "evoke",
      last: "frightful"),
  TsuzutanList(
      id: 'tsuzutan_3_08',
      title: 'つづ単 発展 8',
      level: 3,
      count: 200,
      first: "frivolous",
      last: "honorable"),
  TsuzutanList(
      id: 'tsuzutan_3_09',
      title: 'つづ単 発展 9',
      level: 3,
      count: 200,
      first: "hospitality",
      last: "intersection"),
  TsuzutanList(
      id: 'tsuzutan_3_10',
      title: 'つづ単 発展 10',
      level: 3,
      count: 200,
      first: "interval",
      last: "marble"),
  TsuzutanList(
      id: 'tsuzutan_3_11',
      title: 'つづ単 発展 11',
      level: 3,
      count: 200,
      first: "margin",
      last: "on balance"),
  TsuzutanList(
      id: 'tsuzutan_3_12',
      title: 'つづ単 発展 12',
      level: 3,
      count: 200,
      first: "on standby",
      last: "placebo"),
  TsuzutanList(
      id: 'tsuzutan_3_13',
      title: 'つづ単 発展 13',
      level: 3,
      count: 200,
      first: "placement",
      last: "rake"),
  TsuzutanList(
      id: 'tsuzutan_3_14',
      title: 'つづ単 発展 14',
      level: 3,
      count: 200,
      first: "rally",
      last: "sage"),
  TsuzutanList(
      id: 'tsuzutan_3_15',
      title: 'つづ単 発展 15',
      level: 3,
      count: 200,
      first: "sales quota",
      last: "speaking of which"),
  TsuzutanList(
      id: 'tsuzutan_3_16',
      title: 'つづ単 発展 16',
      level: 3,
      count: 200,
      first: "specialize in",
      last: "take a beating"),
  TsuzutanList(
      id: 'tsuzutan_3_17',
      title: 'つづ単 発展 17',
      level: 3,
      count: 200,
      first: "take after",
      last: "unjust"),
  TsuzutanList(
      id: 'tsuzutan_3_18',
      title: 'つづ単 発展 18',
      level: 3,
      count: 147,
      first: "unkind",
      last: "zealous"),
];
